apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI | b64enc | quote }}
  JWT_PUBLIC: {{ .Values.secrets.JWT_PUBLIC | b64enc | quote }}
