apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-recipe-menu-cronjob
spec:
  schedule: "0 18 * * 0"  # Every Sunday at 6 PM UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: create-menu
              image: curlimages/curl:8.12.0
              command:
                - /bin/sh
                - -c
                - |
                  curl -X GET "http://{{ include "nuri-app.fullname" $ }}/api/cron/create-recipe-menu" \
                  -H "Authorization: Bearer $CRON_SECRET"
              env:
                - name: CRON_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secrets
                      key: CRON_SECRET
          restartPolicy: OnFailure
