apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  JWT_PUBLIC: {{ .Values.secrets.JWT_PUBLIC | b64enc | quote }}
  CRON_SECRET: {{ .Values.secrets.CRON_SECRET | b64enc | quote }}
  EMAIL_FROM: {{ .Values.secrets.EMAIL_FROM | b64enc | quote }}
  EMAIL_SMTP_HOST: {{ .Values.secrets.EMAIL_SMTP_HOST | b64enc | quote }}
  EMAIL_SMTP_LOGIN: {{ .Values.secrets.EMAIL_SMTP_LOGIN | b64enc | quote }}
  EMAIL_SMTP_PORT: {{ .Values.secrets.EMAIL_SMTP_PORT | toString | b64enc | quote }}
  EMAIL_SMTP_PW: {{ .Values.secrets.EMAIL_SMTP_PW | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | b64enc | quote }}
  POSTGRES_URL: {{ .Values.secrets.POSTGRES_URL | b64enc | quote }}
