name: App CI

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: BrummbQ/nuri-app

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: configure env
        env:
          CI_ENV: ${{secrets.CI_ENV}}
        shell: bash
        run: |
          echo "$CI_ENV" > .env.test
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci

  build-and-push-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see [Usage](https://github.com/docker/build-push-action#usage) in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Set up Kubernetes kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" > kubeconfig

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm Chart
        env:
          JWT_PUBLIC: ${{ secrets.APP_JWT_PUBLIC }}
          JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          CRON_SECRET: ${{ secrets.APP_CRON_SECRET }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_LOGIN: ${{ secrets.EMAIL_SMTP_LOGIN }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SMTP_PW: ${{ secrets.EMAIL_SMTP_PW }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          PINECONE_HOSTNAME: ${{ secrets.PINECONE_HOSTNAME }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: |
          helm upgrade --install nuri-app ./infrastructure/charts/nuri-app \
            --kubeconfig kubeconfig \
            --namespace nuri-prod --create-namespace \
            --set image.tag=sha-${{ github.sha }} \
            --set secrets.JWT_SECRET="${JWT_SECRET}" \
            --set secrets.JWT_PUBLIC="${JWT_PUBLIC}" \
            --set secrets.CRON_SECRET="${CRON_SECRET}" \
            --set secrets.EMAIL_FROM="${EMAIL_FROM}" \
            --set secrets.EMAIL_SMTP_HOST="${EMAIL_SMTP_HOST}" \
            --set secrets.EMAIL_SMTP_LOGIN="${EMAIL_SMTP_LOGIN}" \
            --set secrets.EMAIL_SMTP_PORT="${EMAIL_SMTP_PORT}" \
            --set secrets.EMAIL_SMTP_PW="${EMAIL_SMTP_PW}" \
            --set secrets.OPENAI_API_KEY="${OPENAI_API_KEY}" \
            --set secrets.AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
            --set secrets.AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
            --set secrets.PINECONE_HOSTNAME="${PINECONE_HOSTNAME}" \
            --set secrets.PINECONE_API_KEY="${PINECONE_API_KEY}" \
            --wait
