name: Products Api Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    defaults:
      run:
        working-directory: api/products

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: configure env
        env:
          CI_ENV: ${{secrets.CI_PRODUCTS_API_ENV}}
        shell: bash
        run: |
          echo "$CI_ENV" > .env
      - name: Run tests with pytest
        run: |
          pytest
